
app.out: main.o math.o print_functions.o
	gcc -o app.out main.o math.o print_functions.o


main.o: main.c
	gcc -c -o main.o main.c

math.o: math.c
	gcc -c -o math.o math.c

print_functions.o: print_functions.c
	gcc -c -o print_functions.o print_functions.c
